---
- name: Update apt-based systems
  include_tasks: _apt.yaml
  when: ansible_os_family == 'Debian'
  tags:
    - update_sys
    - update_sys_apt
    - update_sys_apt_enabled
    - update_sys_enabled
  ignore_errors: yes