## rpi-update playbook/handlers
- name: reboot
  ansible.builtin.command: /sbin/reboot

- name: apt reboot needed
  ansible.builtin.shell: "[ -f /var/run/reboot-required ]"
  failed_when: false
  register: reboot_required
  changed_when: reboot_required.rc == 0
  notify: reboot

- name: is reboot needed
  debug:
      msg: "Reboot needed!"
  when:
    - reboot_notice in reboot_required
  ignore_errors: True
